package work;

import java.util.HashMap;
import java.util.HashSet;
import java.util.Set;

/*
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

输入给两个只包含小写字母的字符串 S 和 T.

字符串 T 是在字符串 S 基础上添加一个小写字母, 然后随机打乱之后生成.

请找出那个被加入的小写字母.

示例:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
 */
public class Test02 {

    public static void main(String[] args) {
        char a = findTheDifference("abc","abcd");
        System.out.println(a);
    }


    public static  char findTheDifference(String s, String t) {
        HashMap<Character,Integer> hash = new HashMap<>();

        String tmp = s + t;
        for(int i = 0;i<tmp.length();i++){
            char current = tmp.charAt(i);
            if(hash.containsKey(current)){
                hash.put(current,hash.get(current) + 1);
            }else{
                hash.put(current,1);
            }
        }

        Set<Character> a = hash.keySet();
        Character res = null;
        for (Character item: a) {
            if(hash.get(item)==1){
                res = item;
                break;
            }
        }
        return res;
    }
}
